services:
  postgres:
    image: postgres:15-alpine
    container_name: olinnwan-postgres
    restart: always

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olinnwan_db

    ports:
      - '15432:5432'

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
